In [2]:
import requests

In [3]:
web = requests.get("https://www.tutorialspoint.com/index.htm")
print(web)

<Response [200]>

In [4]:
web.content

b'<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta http-equiv="X-UA-Compatible" content="IE=edge">\n<meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=yes, maximum-scale=1">\n<title>Quality Tutorials, Video Courses, and eBooks - TutorialsPoint</title>\n<meta name="Description" content="Learn the latest technologies and programming languages including CodeWhisperer, Google Assistant, Dall-E, Business Intelligence, Claude AI, SwiftUI, Smart Grid Technology, Prompt Engineering, Generative AI, Python, DSA, C, C++, Java, PHP, Machine Learning, Data science etc.">\n<meta name="Keywords" content="CodeWhisperer, Google Assistant, Dall-E, Business Intelligence, Claude AI, SwiftUI, Smart, Grid, Technology, SQL, MySQL, FastAPI, Snowflake, Pyramid, Falcon, XlsxWriter, WebDriverIO, Pygame, HTML, Python, CSS, SQL, JavaScript, How to, PHP, Java, C++, jQuery, Bootstrap, C#, XML, MySQL, NodeJS, React, Angular, R, AI, Git, Data Science, Code Game, Tutorials, Programming, Web Development, Training, Learning, Quiz, Courses, Lessons, References, Examples, Source code, Demos, Tips">\n<meta property="og:image" content="https://www.tutorialspoint.com/images/tp_logo_436.png">\n<meta property="og:image:type" content="image/png">\n<meta property="og:image:width" content="436">\n<meta property="og:image:height" content="228">\n<meta property="og:description" content="Learn the latest technologies and programming languages including CodeWhisperer, Google Assistant, Dall-E, Business Intelligence, Claude AI, SwiftUI, Smart Grid Technology, Prompt Engineering, Generative AI, Python, DSA, C, C++, Java, PHP, Machine Learning, Data science etc.">\n<link rel="icon" href="https://www.tutorialspoint.com/images/favicon.ico?1.0">\n<link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png">\n<link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png">\n<link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png">\n<link rel="canonical" href="https://www.tutorialspoint.com">\n<link rel="preconnect" href="https://fonts.googleapis.com">\n<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n<link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;500;600;700&family=Lato:wght@400;700&family=Poppins:wght@400;500;600&family=Raleway:wght@500&display=swap" rel="stylesheet">\n<link rel="stylesheet" href="/static/css/home.css?v=1.45">\n<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@7/swiper-bundle.min.css">\n<script id="adp1" data-cfasync="false" type="text/javascript">(function(w, d) { var s = d.createElement(\'script\'); s.src = \'//cdn.adpushup.com/40046/adpushup.js\'; s.crossOrigin=\'anonymous\'; s.type = \'text/javascript\'; s.async = true; (d.getElementsByTagName(\'head\')[0] || d.getElementsByTagName(\'body\')[0]).appendChild(s); w.adpushup = w.adpushup || {que:[]}; })(window, document); </script>\n</head>\n<body>\n<div class="accent-header">\n   <nav class="accent-nav library-accent-nav">\n   <div class="accent-nav__content">\n      <ul class="accent-nav__list">\n         <li class="accent-nav__item">\n            <a class="accent-nav__link" href="/index.htm" title="Home"><i class="fa-sharp fa-light fa-home"></i> Home</a>\n         </li>\n\t\t <li class="accent-nav__item mblockMenu">\n\t\t\t<a class=\'accent-nav__link\' href="/tutorialslibrary.htm"><i class="fa-sharp fa-light fa-book-open-reader"></i> Library</a>\n\t\t </li>\n         <li class="accent-nav__item">\n            <a class="accent-nav__link" href="/online-programming-compilers.htm" title="Online Compilers"><i class="fa-sharp fa-light fa-code"></i>Online Compilers</a>\n         </li>\n         <li class="accent-nav__item">\n            <a class="accent-nav__link" href="/job_search.php" title="Jobs"><i class="fa-sharp fa-light fa-suitcase"></i> Jobs</a>\n         </li>\n         <li class="accent-nav__item">\n            <a class="accent-nav__link" href="/whiteboard.htm" title="Whiteboard"><i class="fa-sharp fa-light fa-chalkboard"></i>Whiteboard</a>\n         </li>\n         <li class="accent-nav__item">\n            <a class="accent-nav__link" href="/online_dev_tools.htm" title="Tools"><i class="fa-sharp fa-light fa-tools"></i>Tools</a>\n         </li>\n         <li class="accent-nav__item">\n            <a class=\'accent-nav__link\' href="/articles/index.php" title="Articles"><i class="fa-sharp fa-light fa-pen-to-square"></i>Articles</a>\n         </li>\n         <li class="accent-nav__item">\n            <a class="accent-nav__link" href="https://www.tutorialspoint.com/articles/write-and-earn.php"><i class="fa-sharp fa-light fa-money-check-dollar-pen"></i>Write & Earn</a>\n         </li>\n\t\t <li class="accent-nav__item">\n            <a class="accent-nav__link" href="promote-and-earn.php" title="Promote &amp; Earn"><i class="fa-sharp fa-light fa-chart-mixed-up-circle-dollar"></i>Promote &amp; Earn</a>\n         </li>\n\t\t\t\t <li class="accent-nav__item mblockMenu">\n\t\t\t<a class=\'accent-nav__link\' href="https://www.tutorialspoint.com/market/index.asp"><i class="fa-sharp fa-light fa-money-check-dollar-pen"></i> Courses</a>\n\t\t </li>\n\t\t <li class="accent-nav__item mblockMenu">\n\t\t\t<a class=\'accent-nav__link\' href="https://www.tutorialspoint.com/latest/certifications"><i class="fa-sharp fa-light fa-certificate"></i> Certifications</a>\n\t\t </li>\n      </ul>\n   </div>\n   <span class="topbar">\n\t\t<button class="accent-nav__toggle" aria-expanded="false"> Menu <i class="fa-sharp fa-light fa-angle-down"></i></button>\n\t\t<button aria-expanded="false" class="nav-toggle text-white"> Categories <i class="fa-sharp fa-light fa-angle-down"></i></button>\n\t</span>\t\n   <a href="/market/login.jsp" class="accent-nav__login-button"> Login</a>\n   <ul class="flex-group accent-nav__right-list">\n      <li class="accent-nav__item">\n         <button class="accent-nav__button theme-toggle" aria-expanded="false" href="/index.htm"><span class="sr-only">Switch theme</span></button>\n      </li>\n      <li>\n         <a class="accent-nav__social-link" target="_blank" href="https://www.facebook.com/tutorialspointindia" rel="nofollow"><i class="fa-sharp fa-light fa-brands fa-facebook-f"></i></a>\n      </li>\n\t  <li>\n         <a class="accent-nav__social-link" target="_blank" href="https://twitter.com/tutorialspoint" rel="nofollow"><i class="fa-sharp fa-light fa-brands fa-x-twitter"></i></a>\n      </li>\n\t  <li>\n         <a class="accent-nav__social-link" target="_blank" href="https://www.youtube.com/channel/UCVLbzhxVTiTLiVKeGV7WEBg" rel="nofollow"><i class="fa-sharp fa-light fa-brands fa-youtube"></i></a>\n      </li>\n\t  <li>\n         <a class="accent-nav__social-link" target="_blank" href="https://www.linkedin.com/company/tutorialspoint/" rel="nofollow"><i class="fa-sharp fa-light fa-brands fa-linkedin-in"></i></a>\n      </li>\n      <li>\n         <a class="accent-nav__social-link" target="_blank" href="https://www.instagram.com/tutorialspoint_/" rel="nofollow"><i class="fa-sharp fa-light fa-brands fa-instagram"></i></a>\n      </li>\n   </ul>\n   </nav>\n</div>\n<header class="header show"><a href="https://www.tutorialspoint.com" title="Tutorials point">\n      <svg class="logo-desktop" xmlns="http://www.w3.org/2000/svg" width="226" height="42" viewBox="0 0 226 42" fill="none">\n      <path class="logo-desktop-path" d="M76.2136 13.8408V27.7576H72.3845V26.1045C71.3229 27.3193 69.7701 27.9689 68.0642 27.9689C64.5731 27.9689 62.1172 26.0042 62.1172 21.7103V13.8461H66.1523V21.1135C66.1523 23.4426 67.1874 24.4778 68.9726 24.4778C70.7577 24.4778 72.1785 23.2895 72.1785 20.7279V13.8461H76.2136V13.8408Z" fill="#40A944" />\n      <path class="logo-desktop-path" d="M89.1484 20.7959C89.1484 16.6077 92.3807 13.6289 96.8066 13.6289C101.233 13.6289 104.438 16.6024 104.438 20.7959C104.438 24.9894 101.233 27.9629 96.8066 27.9629C92.3807 27.9629 89.1484 24.9894 89.1484 20.7959ZM100.351 20.7959C100.351 18.3928 98.8242 16.9404 96.8066 16.9404C94.7891 16.9404 93.2363 18.3876 93.2363 20.7959C93.2363 23.2043 94.7891 24.6514 96.8066 24.6514C98.8242 24.6514 100.351 23.2043 100.351 20.7959Z" fill="#40A944" />\n      <path class="logo-desktop-path" d="M115.28 13.6348V17.3582C114.942 17.3318 114.683 17.3054 114.377 17.3054C112.153 17.3054 110.68 18.5202 110.68 21.1873V27.7575H106.645V13.8407H110.5V15.6787C111.482 14.3319 113.141 13.6348 115.285 13.6348H115.28Z" fill="#40A944" />\n      <path class="logo-desktop-path" d="M117.695 13.8408H121.73V27.7576H117.695V13.8408Z" fill="#40A944" />\n      <path class="logo-desktop-path" d="M139.119 13.8402V27.757H135.263V26.1514C134.255 27.3661 132.781 27.9629 130.917 27.9629C126.987 27.9629 123.961 25.169 123.961 20.7959C123.961 16.4228 126.987 13.6289 130.917 13.6289C132.623 13.6289 134.07 14.1729 135.079 15.3084V13.8349H139.114L139.119 13.8402ZM135.163 20.7959C135.163 18.3928 133.61 16.9404 131.619 16.9404C129.628 16.9404 128.049 18.3876 128.049 20.7959C128.049 23.2043 129.602 24.6514 131.619 24.6514C133.637 24.6514 135.163 23.2043 135.163 20.7959Z" fill="#40A944" />\n      <path class="logo-desktop-path" d="M146.402 8.5625H142.367V27.7555H146.402V8.5625Z" fill="#40A944" />\n      <path class="logo-desktop-path" d="M149.141 26.4622L150.487 23.5679C151.729 24.3707 153.619 24.9147 155.325 24.9147C157.19 24.9147 157.887 24.4235 157.887 23.6471C157.887 21.3708 149.479 23.7 149.479 18.1385C149.479 15.4978 151.861 13.6387 155.917 13.6387C157.829 13.6387 159.952 14.077 161.272 14.8534L159.925 17.7266C158.552 16.9502 157.184 16.6914 155.917 16.6914C154.105 16.6914 153.329 17.2618 153.329 17.9854C153.329 20.3673 161.737 18.0646 161.737 23.5468C161.737 26.1347 159.334 27.9674 155.167 27.9674C152.811 27.9674 150.435 27.3231 149.141 26.4675V26.4622Z" fill="#40A944" />\n      <path class="logo-desktop-path" d="M178.226 20.9541C178.226 25.0948 175.332 27.8835 171.45 27.8835C169.279 27.8835 167.415 26.9539 166.279 25.1952V32.7742H164.441V14.1515H166.2V16.8398C167.315 15.0283 169.2 14.0459 171.45 14.0459C175.332 14.0459 178.226 16.8398 178.226 20.9541ZM176.388 20.9541C176.388 17.8011 174.191 15.6515 171.318 15.6515C168.445 15.6515 166.248 17.7958 166.248 20.9541C166.248 24.1125 168.418 26.2568 171.318 26.2568C174.218 26.2568 176.388 24.1336 176.388 20.9541Z" fill="var(--clr-text)" />\n      <path class="logo-desktop-path" d="M180.129 20.9541C180.129 16.919 183.076 14.0459 187.058 14.0459C191.041 14.0459 193.966 16.919 193.966 20.9541C193.966 24.9892 191.046 27.8835 187.058 27.8835C183.071 27.8835 180.129 24.9892 180.129 20.9541ZM192.102 20.9541C192.102 17.7747 189.953 15.6515 187.058 15.6515C184.164 15.6515 181.988 17.7747 181.988 20.9541C181.988 24.1336 184.159 26.2568 187.058 26.2568C189.958 26.2568 192.102 24.1336 192.102 20.9541Z" fill="var(--clr-text)" />\n      <path class="logo-desktop-path" d="M196.754 14.1523H198.592V27.7575H196.754V14.1523Z" fill="var(--clr-text)" />\n      <path class="logo-desktop-path" d="M215.288 19.8661V27.7567H213.45V20.051C213.45 17.1778 211.95 15.7043 209.362 15.7043C206.442 15.7043 204.604 17.5159 204.604 20.6161V27.7567H202.766V14.1515H204.524V16.6602C205.507 15.0071 207.345 14.0459 209.695 14.0459C213.006 14.0459 215.283 15.9578 215.283 19.8661H215.288Z" fill="var(--clr-text)" />\n      <path class="logo-desktop-path" d="M59.3346 24.2389C58.8699 24.5769 58.2731 24.7565 57.6815 24.7565C56.5935 24.7565 55.9756 24.1122 55.9756 22.9185V17.2568H59.4139V14.1512H55.9756V10.2852L51.9405 11.2411V14.1512H50.2188V17.2568H51.9405V22.9714C51.9405 26.2829 53.8313 27.9624 57.1375 27.9624C58.3523 27.9624 59.567 27.6772 60.3962 27.0804L59.3346 24.2336V24.2389Z" fill="#40A944" />\n      <path class="logo-desktop-path" d="M87.2878 24.2389C86.823 24.5769 86.2262 24.7565 85.6347 24.7565C84.5467 24.7565 83.9287 24.1122 83.9287 22.9185V17.2568H87.367V14.1512H83.9287V10.2852L79.8936 11.2411V14.1512H78.1719V17.2568H79.8936V22.9714C79.8936 26.2829 81.7844 27.9624 85.0907 27.9624C86.3054 27.9624 87.5202 27.6772 88.3494 27.0804L87.2878 24.2336V24.2389Z" fill="#40A944" />\n      <path class="logo-desktop-path" d="M119.713 11.8222C120.827 11.8222 121.73 10.9189 121.73 9.80465C121.73 8.69039 120.827 7.78711 119.713 7.78711C118.599 7.78711 117.695 8.69039 117.695 9.80465C117.695 10.9189 118.599 11.8222 119.713 11.8222Z" fill="#40A944" />\n      <path class="logo-desktop-path" d="M197.674 11.8222C198.788 11.8222 199.691 10.9189 199.691 9.80465C199.691 8.69039 198.788 7.78711 197.674 7.78711C196.56 7.78711 195.656 8.69039 195.656 9.80465C195.656 10.9189 196.56 11.8222 197.674 11.8222Z" fill="#40A944" />\n      <path class="logo-desktop-path" d="M225.15 25.6071C224.633 26.0719 223.909 26.3043 223.133 26.3043C221.606 26.3043 220.803 25.4223 220.803 23.822V15.699H224.918V14.1462H220.803V10.2168L218.965 11.1728V14.1462H217.043V15.699H218.965V23.9223C218.965 26.4311 220.386 27.8782 222.948 27.8782C224.009 27.8782 225.097 27.5666 225.794 26.9222L225.15 25.6019V25.6071Z" fill="var(--clr-text)" />\n      <path d="M27.3002 39.5829C33.1626 39.4561 38.4072 35.87 40.8842 30.5568C42.3208 27.4829 43.0444 24.013 42.8542 20.3582C42.2785 9.30395 33.1521 0.394029 22.082 0.0718569C9.95038 -0.282005 0 9.44655 0 21.5043C0 30.7099 5.80439 38.5583 13.9485 41.6004C13.1721 40.7871 12.6017 39.7941 12.2531 38.6217C11.7091 36.8101 11.725 34.6711 12.2954 32.2046L15.2319 19.8881H9.16343L10.1564 15.5837L10.4257 14.4429H16.5259L16.6368 13.9411L18.0628 7.76175L26.9727 6.05582L25.1506 13.9411L23.8408 19.8881L20.8197 33.2609C20.3602 35.2626 20.5398 36.8101 21.3743 37.8928C21.3743 37.8928 22.6207 39.6832 27.3002 39.5829ZM29.4128 13.4605C31.8951 12.9904 34.0288 15.1242 33.5588 17.6065C33.2947 18.9902 32.1803 20.1099 30.7912 20.374C28.3089 20.8441 26.1752 18.7103 26.6453 16.228C26.9093 14.8443 28.0237 13.7246 29.4128 13.4605Z" fill="#40A944" />\n      </svg>\n      <svg class="logo-mobile" xmlns="http://www.w3.org/2000/svg" width="43" height="42" viewBox="0 0 43 42" fill="none"><path d="M27.3002 39.5829C33.1626 39.4561 38.4072 35.87 40.8842 30.5568C42.3208 27.4829 43.0444 24.013 42.8542 20.3582C42.2785 9.30395 33.1521 0.394029 22.082 0.0718569C9.95038 -0.282005 0 9.44655 0 21.5043C0 30.7099 5.80439 38.5583 13.9485 41.6004C13.1721 40.7871 12.6017 39.7941 12.2531 38.6217C11.7091 36.8101 11.725 34.6711 12.2954 32.2046L15.2319 19.8881H9.16343L10.1564 15.5837L10.4257 14.4429H16.5259L16.6368 13.9411L18.0628 7.76175L26.9727 6.05582L25.1506 13.9411L23.8408 19.8881L20.8197 33.2609C20.3602 35.2626 20.5398 36.8101 21.3743 37.8928C21.3743 37.8928 22.6207 39.6832 27.3002 39.5829ZM29.4128 13.4605C31.8951 12.9904 34.0288 15.1242 33.5588 17.6065C33.2947 18.9902 32.1803 20.1099 30.7912 20.374C28.3089 20.8441 26.1752 18.7103 26.6453 16.228C26.9093 14.8443 28.0237 13.7246 29.4128 13.4605Z" fill="#40A944" /></svg>\n   </a>\n   <nav class="nav">\n   <ul class="nav__list">\n   <li class="nav__item dropdown">\n   <button aria-expanded="false" aria-controls="category" class="flex-group dropdown__toggle button-reset" style="--gap: .5rem;"><i class="fa-sharp fa-light fa-grid-2"></i>\n   <span class="flex-group" style="--gap: 0.25rem;">\n   <span>Category</span><i class="fa-sharp fa-light fa-angle-down"></i>\n   </span>\n   </button>\n   <div class="dropdown__list-wrapper">\n   <div class=" categories-menu">\n   <div class="">\n   <ul>\n      <li class="category-button" aria-selected="true" role="tab">AI, ML, and Data Science<i class="fa-sharp fa-light fa-angle-right"></i></li>\n      <li class="category-button" role="tab">Programming Languages<i class="fa-sharp fa-light fa-angle-right"></i></li>\n      <li class="category-button" role="tab">Web Development Languages<i class="fa-sharp fa-light fa-angle-right"></i></li>\n      <li class="category-button" role="tab">DevOps<i class="fa-sharp fa-light fa-angle-right"></i></li>\n      <li class="category-button" role="tab">Databases<i class="fa-sharp fa-light fa-angle-right"></i></li>\n      <li class="category-button" role="tab">Computer Science Subjects<i class="fa-sharp fa-light fa-angle-right"></i></li>\n      <li class="category-button" role="tab">Python Technologies<i class="fa-sharp fa-light fa-angle-right"></i></li>\n      <li class="category-button" role="tab">Software Testing<i class="fa-sharp fa-light fa-angle-right"></i></li>\n      <li class="category-button" role="tab">Cyber Security<i class="fa-sharp fa-light fa-angle-right"></i></li>\n      <li class=""><a href="/top-categories.htm" class="button w100 mt-2" title="All Categories"><i class="fa-sharp fa-light fa-cubes"></i> All Categories </a></li>\n   </ul>\n\n   <div class="categories-menu-content">\n   <div class="categories-menu-sections-wrapper">\n\n   <!-- AI, ML Data Science -->\n   <div class="categories-menu-section">\n      <button class="button button--neutral categories-menu-section__back-button">\n          <i class="fa-sharp fa-light fa-angle-right"></i> Back\n      </button>\n      <ul>\n         <li><a href="/artificial_intelligence/index.htm">Artificial Intelligence</a></li>\n         <li><a href="/machine_learning/index.htm">Machine Learning</a></li>\n         <li><a href="/machine_learning_with_python/index.htm">ML With Python</a></li>\n         <li><a href="/data_science/index.htm">Data Science</a></li>\n         <li><a href="/statistics/index.htm">Statistics</a></li>\n      </ul>\n      <ul>\n         <li><a href="/natural_language_processing/index.htm">NLP</a></li>\n         <li><a href="/artificial_neural_network/index.htm">Neural Networks</a></li>\n         <li><a href="/tensorflow/index.htm">TensorFlow</a></li>\n         <li><a href="/pytorch/index.htm">PyTorch</a></li>\n         <li><a href="/matplotlib/index.htm">Matplotlib</a></li>\n      </ul>\n      <ul>\n         <li><a href="/numpy/index.htm">NumPy</a></li>\n         <li><a href="/python_pandas/index.htm">Pandas</a></li>\n         <li><a href="/scipy/index.htm">SciPy</a></li>\n         <li><a href="/big_data_analytics/index.htm">Big Data Analytics</a></li>\n         <li><a href="/machine_learning_tutorials.htm" class="w100">See all</a></li>\n      </ul>\n   </div>\n\n   <!-- Programming Languages -->\n   <div class="categories-menu-section">\n      <button class="button button--neutral categories-menu-section__back-button">\n          <i class="fa-sharp fa-light fa-angle-right"></i> Back\n      </button>\n      <ul>\n         <li><a href="/python/index.htm">Python</a></li>\n         <li><a href="/java/index.htm">Java</a></li>\n         <li><a href="/cplusplus/index.htm">C++</a></li>\n         <li><a href="/cprogramming/index.htm">C</a></li>\n         <li><a href="/php/index.htm">PHP</a></li>\n         <li><a href="/go/index.htm">Go</a></li>\n      </ul>\n      <ul>\n         <li><a href="/kotlin/index.htm">Kotlin</a></li>\n         <li><a href="/r/index.htm">R</a></li>\n         <li><a href="/asp.net/index.htm">ASP.Net</a></li>\n         <li><a href="/csharp/index.htm">C#.Net</a></li>\n         <li><a href="/vb.net/index.htm">VB.Net</a></li>\n         <li><a href="/scala/index.htm">Scala</a></li>\n      </ul>\n      <ul>\n         <li><a href="/swift/index.htm">Swift</a></li>\n         <li><a href="/perl/index.htm">Perl</a></li>\n         <li><a href="/ruby/index.htm">Ruby</a></li>\n         <li><a href="/rust/index.htm">Rust</a></li>\n         <li><a href="/lua/index.htm">Lua</a></li>\n         <li><a href="/computer_programming_tutorials.htm" class="w100">See all</a></li>\n      </ul>\n   </div>\n\n   <!-- Web Development Languages -->\n   <div class="categories-menu-section">\n      <button class="button button--neutral categories-menu-section__back-button">\n          <i class="fa-sharp fa-light fa-angle-right"></i> Back\n      </button>\n      <ul>\n         <li><a href="/html/index.htm">HTML</a></li>\n         <li><a href="/css/index.htm">CSS</a></li>\n         <li><a href="/javascript/index.htm">JavaScript</a></li>\n         <li><a href="/jquery/index.htm">jQuery</a></li>\n         

In [5]:
from bs4 import BeautifulSoup

In [6]:
web = requests.get("https://www.tutorialspoint.com/index.htm")

In [7]:
web.status_code

200

In [8]:
soup = BeautifulSoup(web.content, "html.parser")

In [9]:
para = soup.find_all('p')
para

[<p class="hero-slider__number">10,000+</p>,
 <p class="hero-slider__text">Video Courses</p>,
 <p class="hero-slider__number">5,000+</p>,
 <p class="hero-slider__text">Expert Trainers</p>,
 <p class="hero-slider__number">100M+</p>,
 <p class="hero-slider__text">Learners Served</p>,
 <p class="hero-slider__number">50,000+</p>,
 <p class="hero-slider__text">Learning Hours</p>,
 <p class="mt rtext">Become an expert in top technologies with our extensive online certification programs</p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">8</span> Courses | <span class="fw-600">1</span> eBook</p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">7</span> Courses | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">9</span> Courses | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">7</span> Courses | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">9</span> Courses | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">8</span> Courses | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutoriaspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">8</span> Courses | <span class="fw-600">1</span> eBook</p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">7</span> Courses | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">7</span> Courses | <span class="fw-600">1</span> eBook</p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">4</span> Courses | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">8</span> Courses 					 | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">7</span> Courses | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">9</span> Courses | <span class="fw-600">1</span> eBook</p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">7</span> Courses 					 | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">9</span> Courses | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">7</span> Courses | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">8</span> Courses 					 | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">8</span> Courses 					 | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">7</span> Courses 					 | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">7</span> Courses | <span class="fw-600">1</span> eBook </p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">4</span> Courses | <span class="fw-600">1</span> eBook</p>,
 <p><a href="https://www.tutorialspoint.com/profile/tutorialspoint_com" target="_blank">Tutorialspoint</a></p>,
 <p class="fs-300"><span class="fw-600">7</span> Courses | <span class="fw-600">1</span> eBook </p>,
 <p class="fw-600">Become a valued member of Tutorials Point and enjoy unlimited access to our vast library of top-rated Video Courses</p>,
 <p class="mt">Newly Added and Updated Tutorials</p>,
 <p class="fs-550 fw-600">Coding Ground For Developers</p>,
 <p class="yellow-accent-text">Code, Edit, Run and Share</p>,
 <p class="coding-ground__description fs-300">Ignite your coding potential on Coding Ground - an immersive online platform for hands-on learning, collaboration, and skill development.</p>,
 <p>Master any technology with our largest free online Library</p>,
 <p class="library-item__description sprite-img-title">Bitcoin Tutorial</p>,
 <p class="library-item__description sprite-img-title">Blockchain Tutorial</p>,
 <p class="library-item__description sprite-img-title">Blue Prism</p>,
 <p class="library-item__description sprite-img-title">Ethereum Tutorial</p>,
 <p class="library-item__description sprite-img-title">Python Blockchain</p>,
 <p class="library-item__description sprite-img-title">Computer Fundamentals</p>,
 <p class="library-item__description sprite-img-title">Compiler Design</p>,
 <p class="library-item__description sprite-img-title">Operating System</p>,
 <p class="library-item__description sprite-img-title">Data Structure</p>,
 <p class="library-item__description sprite-img-title">DBMS Tutorial</p>,
 <p class="library-item__description sprite-img-title">Machine Learning</p>,
 <p class="library-item__description sprite-img-title">TensorFlow Tutorial</p>,
 <p class="library-item__description sprite-img-title">ML with Python</p>,
 <p class="library-item__description sprite-img-title">AI with Python</p>,
 <p class="library-item__description sprite-img-title">Time Series</p>,
 <p class="library-item__description sprite-img-title">HTML Tutorial</p>,
 <p class="library-item__description sprite-img-title">CSS Tutorial</p>,
 <p class="library-item__description sprite-img-title">Javascript Tutorial</p>,
 <p class="library-item__description sprite-img-title">PHP Tutorial</p>,
 <p class="library-item__description sprite-img-title">Angular 4 Tutorial</p>,
 <p class="library-item__description sprite-img-title">HTML Tutorial</p>,
 <p class="library-item__description sprite-img-title">C++ Tutorial</p>,
 <p class="library-item__description sprite-img-title">Java8 Tutorial</p>,
 <p class="library-item__description sprite-img-title">Python Tutorial</p>,
 <p class="library-item__description sprite-img-title">Scala Tutorial</p>,
 <p class="library-item__description sprite-img-title">Java8 Tutorial</p>,
 <p class="library-item__description sprite-img-title">JDBC Tutorial</p>,
 <p class="library-item__description sprite-img-title">SWING Tutorial</p>,
 <p class="library-item__description sprite-img-title">Servlets Tutorial</p>,
 <p class="library-item__description sprite-img-title">Spring Tutorial</p>,
 <p class="library-item__description sprite-img-title">Android Tutorial</p>,
 <p class="library-item__description sprite-img-title">Swift Tutorial</p>,
 <p class="library-item__description sprite-img-title">IOS Tutorial</p>,
 <p class="library-item__description sprite-img-title">Kotlin Tutorial</p>,
 <p class="library-item__description sprite-img-title">Xamarian Tutorial</p>,
 <p class="library-item__description sprite-img-title">Mongo DB Tutorial</p>,
 <p class="library-item__description sprite-img-title">PL / SQL Tutorial</p>,
 <p class="library-item__description sprite-img-title">SQL Tutorial</p>,
 <p class="library-item__description sprite-img-title">DB2 Tutorial</p>,
 <p class="library-item__description sprite-img-title">MySQL Tutorial</p>,
 <p class="library-item__description sprite-img-title">ASP.NET</p>,
 <p class="library-item__description sprite-img-title">Entity Framework</p>,
 <p class="library-item__description sprite-img-title">VB.NET Tutorial</p>,
 <p class="library-item__description sprite-img-title">Microsoft Project</p>,
 <p class="library-item__description sprite-img-title">Microsoft Excel</p>,
 <p class="library-item__description sprite-img-title">Big Data Analytics</p>,
 <p class="library-item__description sprite-img-title">Hadoop Tutorial</p>,
 <p class="library-item__description sprite-img-title">SAS Tutorial</p>,
 <p class="library-item__description sprite-img-title">QlikView Tutorial</p>,
 <p class="library-item__description sprite-img-title">Power BI Tutorial</p>,
 <p class="mt">Utilize the frequently used tools for your needs </p>,
 <p>Become a valued member of Tutorials Point and enjoy unlimited access to our vast library of top-rated Video Courses</p>,
 <p>Master prominent technologies at full length and become a valued certified professional.</p>,
 <p>
 <p class="">Tutorials Point is a leading Ed Tech company striving to provide the best learning material on technical and non-technical subjects.</p>
 </p>,
 <p class="">Tutorials Point is a leading Ed Tech company striving to provide the best learning material on technical and non-technical subjects.</p>,
 <p class="footer__copyright">© Copyright 2025. All Rights Reserved.</p>]

In [10]:
for p in para:
    print(p.text)

10,000+
Video Courses
5,000+
Expert Trainers
100M+
Learners Served
50,000+
Learning Hours
Become an expert in top technologies with our extensive online certification programs
Tutorialspoint
8 Courses | 1 eBook
Tutorialspoint
7 Courses | 1 eBook
Tutorialspoint
9 Courses | 1 eBook
Tutorialspoint
7 Courses | 1 eBook
Tutorialspoint
9 Courses | 1 eBook
Tutorialspoint
8 Courses | 1 eBook
Tutorialspoint
8 Courses | 1 eBook
Tutorialspoint
7 Courses | 1 eBook
Tutorialspoint
7 Courses | 1 eBook
Tutorialspoint
4 Courses | 1 eBook
Tutorialspoint
8 Courses 					 | 1 eBook
Tutorialspoint
7 Courses | 1 eBook
Tutorialspoint
9 Courses | 1 eBook
Tutorialspoint
7 Courses 					 | 1 eBook
Tutorialspoint
9 Courses | 1 eBook
Tutorialspoint
7 Courses | 1 eBook
Tutorialspoint
8 Courses 					 | 1 eBook
Tutorialspoint
8 Courses 					 | 1 eBook
Tutorialspoint
7 Courses 					 | 1 eBook
Tutorialspoint
7 Courses | 1 eBook
Tutorialspoint
4 Courses | 1 eBook
Tutorialspoint
7 Courses | 1 eBook
Become a valued member of Tutorials Point and enjoy unlimited access to our vast library of top-rated Video Courses
Newly Added and Updated Tutorials
Coding Ground For Developers
Code, Edit, Run and Share
Ignite your coding potential on Coding Ground - an immersive online platform for hands-on learning, collaboration, and skill development.
Master any technology with our largest free online Library
Bitcoin Tutorial
Blockchain Tutorial
Blue Prism
Ethereum Tutorial
Python Blockchain
Computer Fundamentals
Compiler Design
Operating System
Data Structure
DBMS Tutorial
Machine Learning
TensorFlow Tutorial
ML with Python
AI with Python
Time Series
HTML Tutorial
CSS Tutorial
Javascript Tutorial
PHP Tutorial
Angular 4 Tutorial
HTML Tutorial
C++ Tutorial
Java8 Tutorial
Python Tutorial
Scala Tutorial
Java8 Tutorial
JDBC Tutorial
SWING Tutorial
Servlets Tutorial
Spring Tutorial
Android Tutorial
Swift Tutorial
IOS Tutorial
Kotlin Tutorial
Xamarian Tutorial
Mongo DB Tutorial
PL / SQL Tutorial
SQL Tutorial
DB2 Tutorial
MySQL Tutorial
ASP.NET
Entity Framework
VB.NET Tutorial
Microsoft Project
Microsoft Excel
Big Data Analytics
Hadoop Tutorial
SAS Tutorial
QlikView Tutorial
Power BI Tutorial
Utilize the frequently used tools for your needs
Become a valued member of Tutorials Point and enjoy unlimited access to our vast library of top-rated Video Courses
Master prominent technologies at full length and become a valued certified professional.

Tutorials Point is a leading Ed Tech company striving to provide the best learning material on technical and non-technical subjects.

Tutorials Point is a leading Ed Tech company striving to provide the best learning material on technical and non-technical subjects.
© Copyright 2025. All Rights Reserved.

In [11]:
s1 = soup.find("h3", class_ = "fs-400 fw-700")
# for l in s1:
    
print(s1.text)

 DevOps Certification 2025

In [48]:
headers = {
        "User-Agent": "Mozilla/5.0",
        "Accept": "application/json",
    }

web2 = requests.get("https://www.accessdata.fda.gov/scripts/cdrh/cfdocs/cfPMA/pss.cfm", headers=headers)
soup = BeautifulSoup(web2.content, "html.parser")

s2 = soup.find_all("h1", id = "topic_page_title")
for i in s2:
    print(i.text)

522 Postmarket Surveillance Studies Database

In [49]:
import pandas as pd

s3 = soup.find_all("td")
for t in s3:
    print(t.text)

	To search for Manufacturer beginning with a specific letter, select that letter










							 A














							 B














							 C














							 D














							 E














							 F














							 G














							 H














							 I














							 J














							 L














							 M














							 N














							 O














							 P














							 R














							 S














							 T














							 U














							 V














							 W














							 X














							 Z




















							 A













							 A







							 A









							 B













							 B







							 B









							 C













							 C







							 C









							 D













							 D







							 D









							 E













							 E







							 E









							 F













							 F







							 F









							 G













							 G







							 G









							 H













							 H







							 H









							 I













							 I







							 I









							 J













							 J







							 J









							 L













							 L







							 L









							 M













							 M







							 M









							 N













							 N







							 N









							 O













							 O







							 O









							 P













							 P







							 P









							 R













							 R







							 R









							 S













							 S







							 S









							 T













							 T







							 T









							 U













							 U







							 U









							 V













							 V







							 V









							 W













							 W







							 W









							 X













							 X







							 X









							 Z













							 Z







							 Z







331 orders








  Inactive Orders





Suggest Enhancement / Report Issue |
				Export to Excel






  Inactive Orders





Suggest Enhancement / Report Issue |
				Export to Excel


  Inactive Orders





Suggest Enhancement / Report Issue |
				Export to Excel





Suggest Enhancement / Report Issue |
				Export to Excel


Suggest Enhancement / Report Issue |
				Export to Excel






522OrderNumber

















Manufacturer
















DeviceName
















MedicalSpecialty
















Date 522Order













StudyName




Study Status



PS120001

Acell, Inc.
Acell matristem pelvic floor matrix
General & Plastic Surgery
01/03/2012

POP AE and Effectiveness rates, registry

Completed

PS110124

Advanced Bioresearch Association
Natural lock acetabular component
Orthopedic
05/06/2011

Metal ion levels

Terminated

PS110125

Advanced Bioresearch Association
Muller titanium backed acetabular cup component
Orthopedic
05/06/2011

Metal ion levels

Terminated

PS110126

Advanced Bioresearch Association
Pm cementless screw-in acetabular cup
Orthopedic
05/06/2011

Metal ion levels

Terminated

PS110127

Advanced Bioresearch Association
Weill cementless threaded acetabular cup
Orthopedic
05/06/2011

Metal ion levels

Terminated

PS110128

Advanced Bioresearch Association
Freeman acetabular cup
Orthopedic
05/06/2011

Metal ion levels

Terminated

PS130043

Aesculap, Inc.
Ring upm total hip replacement
Orthopedic
07/29/2013

PSS

Terminated

PS130045

Aesculap, Inc.
Modular range of ring pros. For hip replacement
Orthopedic
07/29/2013

PSS

Terminated

PS090002

Alphatec Spine
Zodiac dynamo semi-rigid spinal system
Orthopedic
10/05/2009

Fusion, AEs, Surg Procedures

Terminated

PS090012

Alphatec Spine
Isobar semi-rigid spinal system & dual dampener
Orthopedic
10/05/2009

Fusion, AEs, Surg Procedures

Terminated

PS120002

American Medical Systems, Inc.
Ams large pore polypropylene mesh
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

PS120003

American Medical Systems, Inc.
Ams large pore polypropylene mesh
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

PS120005

American Medical Systems, Inc.
Ams elevate anterior & apical prolapse repair system with intepro lite
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

PS120007

American Medical Systems, Inc.
Ams elevate apical and posterior prolapse repair system with intepro lite or intexen lp
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

PS120008

American Medical Systems, Inc.
Ams elevate apical and posterior prolapse repair system with intepro lite or intexen lp
Obstetrics/Gynecology
01/03/2012

AE and Effectiveness Rates

Other

PS120009

American Medical Systems, Inc.
Apogee and perigee systems with intepro lite and intexen lp part of the ams pelvic floor repair system; Ams collagen dermal matrix, ams apogee system with pre-connected collagen dermal matrix, ams perigee system with pre-connected collagen dermal matrix
Obstetrics/Gynecology
01/03/2012

Apogee and Perigee System w/IntePro Lite

Other

PS120010

American Medical Systems, Inc.
Apogee and perigee systems with intepro lite and intexen lp part of the ams pelvic floor repair system; Ams collagen dermal matrix, ams apogee system with pre-connected collagen dermal matrix, ams perigee system with pre-connected collagen dermal matrix
Obstetrics/Gynecology
01/03/2012

Apogee  AE and Eff Rates

Other

Perigee AE and Eff Rates

Other

PS120011

American Medical Systems, Inc.
Apogee and perigee systems with intepro lite and intexen lp part of the ams pelvic floor repair system; Ams collagen dermal matrix, ams apogee system with pre-connected collagen dermal matrix, ams perigee system with pre-connected collagen dermal matrix
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

PS120012

American Medical Systems, Inc.
Apogee and perigee systems with intepro lite and intexen lp part of the ams pelvic floor repair system; Ams collagen dermal matrix, ams apogee system with pre-connected collagen dermal matrix, ams perigee system with pre-connected collagen dermal matrix
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

PS120013

American Medical Systems, Inc.
Apogee and perigee systems with pc coated intepro lite
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

PS120014

American Medical Systems, Inc.
Elevate prolapse repair system with pc coated intepro lite- apical and posterior prolapse repair system anterior and ap
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

PS120015

American Medical Systems, Inc.
Ams collagen dermal matrix, ams apogee system with pre-connected collagen dermal matrix, ams perigee system with pre-connected collagen dermal matrix
General & Plastic Surgery
01/03/2012

AE and effectiveness rates

Other

PS120090

American Medical Systems, Inc.
Miniarc precise single-incision sling system
Gastroenterology/Urology
01/03/2012

AE and effectiveness rates

Other

PS120091

American Medical Systems, Inc.
Miniarc precise single-incision sling system
Gastroenterology/Urology
01/03/2012

SUI AE and Effectiveness rates

Consolidated

PS120092

American Medical Systems, Inc.
Miniarc precise single-incision sling system
Gastroenterology/Urology
01/03/2012

SUI AE and Effectiveness rates

Consolidated

PS130011

American Medical Systems, Inc.
Elevate prolapse repair systems
Obstetrics/Gynecology
03/13/2013

AE & Effectiveness Rates

Consolidated

PS130017

American Medical Systems, Inc.
Ams triangle silicone-coated sling and surgical mesh
General & Plastic Surgery
03/13/2013

PSS

Other

PS130018

American Medical Systems, Inc.
Topas system
General & Plastic Surgery
03/13/2013

PSS

Other

PS130019

American Medical Systems, Inc.
Pfr sling system, (part of the pelvic floor repair system)
General & Plastic Surgery
03/13/2013

PSS

Other

PS130037

American Medical Systems, Inc.
Miniarc pro single-incision sling system
Gastroenterology/Urology
03/13/2013

PSS

Consolidated

PS110129

American Ortomed Corp.
Titanium mittelmeier type acetabular
Orthopedic
05/06/2011

Metal ion levels

Terminated

PS110130

American Ortomed Corp.
Uniloc-cementless & self tap acetabular
Orthopedic
05/06/2011

Metal ion levels

Terminated

PS100002

Amsino International, Inc
Cortez needle free iv connector
General Hospital
07/21/2010

BSI rate

Other

PS090003

Applied Spine Technologies, Inc.
Bar pedicle screw spinal fixation system
Orthopedic
10/05/2009

Fusion, AEs, Surg Procedures

Terminated

PS140001

Argo Medical Technologies, Inc
Rewalk
Neurology
06/26/2014

ReWalk RWE Study

Completed

PS120004

Astora Womens Health
Ams elevate anterior & apical prolapse repair system with intepro llite
Obstetrics/Gynecology
01/03/2012

POP AE and effectiveness rates, registry

Other

PS120006

Astora Womens Health
Ams elevate apical and posterior prolapse repair system with intepro lite
Obstetrics/Gynecology
01/03/2012

POP AE and Effectiveness rates, registry

Other

Elevate System w/InteXen LP

Other

PS120089

Astora Womens Health
Miniarc precise single-incision sling system
Gastroenterology/Urology
01/03/2012

SUI AE and Effectiveness rates

Other

PS180001

Avenu Medical, Inc.
Ellipsys vascular access system
Cardiovascular
06/21/2018

Postmarket Study

Terminated

PS100006

B. Braun Medical Inc.
Ultrasite valve
General Hospital
07/21/2010

BSI rate

Completed

PS140002

Bard Peripheral Perivascular
Simon Nitinol System
Cardiovascular
10/17/2014

Simon Nitinol PS

Other

PS130042

Baxter Healthcare Corp
Vena Cava Filter
Cardiovascular
07/29/2013

PSS

Other

PS100007

Baxter Healthcare Corporation
Iv/catheter extension set with nac plus needleless access connector and nac plus needleless access connector
General Hospital
07/21/2010

BSI rate

Other

PS100008

Becton Dickinson Infusion Therapy Systems
Bd posiflow/tm positive displacement valve
General Hospital
07/21/2010

BSI rate

Other

PS100011

Becton Dickinson Infusion Therapy Systems
Nima needleless injectionsite master adapter with posiflow positive displacement feature, and iv sets
General Hospital
07/21/2010

BSI rate

Other

PS110005

Biomet Inc.
Porous titanium acetabular augments, m2a magnum 12/14 taper inserts and one-piece modular heads
Orthopedic
05/06/2011

Metal Ion Levels

Completed

Explant Analysis

Completed

PS110006

Biomet Inc.
M2a magnum 12/14 taper inserts and one-piece modular heads
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110007

Biomet Inc.
Lateralized taperloc microplasty femoral components
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110008

Biomet Inc.
M2a-magnum tri-spike acetabular component
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110009

Biomet Inc.
Altra press-fit hip system
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110010

Biomet Inc.
Altra fx hip system
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110011

Biomet Inc.
Echo bi-metric press-fit stems
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110012

Biomet Inc.
Parallel-sided extensively coated femoral stems
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110013

Biomet Inc.
Compress segmental femoral replacement system (short spindle and anchor plug)
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110014

Biomet Inc.
Metal on metal acetabular system
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110015

Biomet Inc.
M2a 28mm ringloc liner
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110016

Biomet Inc.
M2a acetabular system
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110017

Biomet Inc.
M2a magnum system
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110018

Biomet Inc.
Mallory-head modular calcar stems with interlocking slots
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110019

Biomet Inc.
M2a/c2a acetabular system
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110020

Biomet Inc.
Porous coated acetabular components
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110021

Biomet Inc.
Compress segmental femoral replacement system
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110022

Biomet Inc.
Biomet metal-on-metal hip systems- expanded contraindications
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110023

Biomet Inc.
Biomet modular femoral revision system
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110024

Biomet Inc.
Balance hip system
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110025

Biomet Inc.
Taper 2 porous femoral stem
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110026

Biomet Inc.
Ringloc + hybrid acetabular system
Orthopedic
05/06/2011

Metal Ion Levels

Consolidated

PS110004

Biomet Microfixation
Total temporomandibular joint replacement system
Dental
02/04/2011

Time to Revision

Completed

Explant

Completed

PS090004

Biospine Co., Ltd.
Bioflex®
Orthopedic
10/05/2009

Fusion, AEs, Surg Procedures

Terminated

PS120081

Boston Scientific
Xenform soft tissue repair matrix
General & Plastic Surgery
01/03/2012

POP AE and Effectiveness rates, registry

Completed

PS120021

Boston Scientific Corporation
Lite pelvic floor repair kits
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates for Uphold LITE

Other

DUET LITE

Other

Posterior LITE

Other

Anterior LITE

Other

PS120022

Boston Scientific Corporation
Pelvic floor repair system (pinnacle duet)
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates-Duet

Other

PS120023

Boston Scientific Corporation
Pinnacle pelvic floor repair kit ii (uphold)
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates-Uphold

Other

PS120024

Boston Scientific Corporation
Pinnacle pelvic floor repair kits (pinnacle)
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates-Anterior

Other

Posterior

Other

PS120093

Boston Scientific Corporation
Solyx Single Incision Sling System
Gastroenterology/Urology
01/03/2012

SUI AE and Effectiveness rates

Completed

PS130001

Boston Scientific Corporation
Greenfield vena cava filters
Cardiovascular
02/28/2013

Greenfield PS study

Completed

PS130002

Boston Scientific Corporation
Vena cava filters
Cardiovascular
02/28/2013

Greenfield PS study

Completed

PS130020

Boston Scientific Corporation
Surgical fabrics
General & Plastic Surgery
03/13/2013

PSS

Other

PS130021

Boston Scientific Corporation
Modification to trelex mesh surgical mesh
Gastroenterology/Urology
03/13/2013

PSS

Terminated

PS130022

Boston Scientific Corporation
Modification to Surgical Mesh Polymeric
Gastroenterology/Urology
03/13/2013

PSS

Terminated

PS130044

Boston Scientific Corporation
Pinnacle LITE Pelvic Floor Repair Kits - Uphold Lite Posterior and Uphold
Obstetrics/Gynecology
07/03/2013

POP AE and Effectiveness rates, registry

Completed

Posterior Lite

Other

PS110131

C.R. Bard Inc.
CONTOUR II LINK SP TOTAL HIP PROSTHESIS
Orthopedic
05/06/2011

Metal ion levels

Terminated

PS120027

C.R. Bard Inc.
Avaulta solo synthetic support system avaulta plus biosynthetic support system; Avaulta support system
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

PS120028

C.R. Bard Inc.
Avaulta solo synthetic support system avaulta plus biosynthetic support system; Avaulta support system
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

PS120029

C.R. Bard Inc.
Avaulta solo synthetic support system avaulta plus biosynthetic support system; Avaulta support system
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

PS120030

C.R. Bard Inc.
Bard prolapse repair system
General & Plastic Surgery
01/03/2012

AE and effectiveness rates

Terminated

PS120031

C.R. Bard Inc.
Bard pelvisoft acellular collagen biomesh
General & Plastic Surgery
01/03/2012

AE and effectiveness rates

Other

PS120094

C.R. Bard Inc.
Ajust adjustable single incision sling
Gastroenterology/Urology
01/03/2012

AE and effectiveness rates

Other

PS130038

C.R. Bard Inc.
Ajust helical adjustable single-incision sling
Gastroenterology/Urology
03/13/2013

PSS

Other

PS120032

Caldera Medical Inc.
Popmesh
General & Plastic Surgery
01/03/2012

AE and effectiveness rates-PoP Mesh

Other

PS120033

Caldera Medical Inc.
Ascend blue ac mesh; Ascend blue pc mesh
General & Plastic Surgery
01/03/2012

AE and effectiveness rates

Other

PS120034

Caldera Medical Inc.
Ascend blue ac mesh; Ascend blue pc mesh
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

PS120102

Caldera Medical Inc.
Desara mini
Gastroenterology/Urology
04/09/2012

AE & Effectiveness Rates

Other

PS130023

Caldera Medical Inc.
T-sling
Gastroenterology/Urology
03/13/2013

PSS

Terminated

PS130024

Caldera Medical Inc.
Caldera mesh
General & Plastic Surgery
03/13/2013

PSS

Other

PS130025

Caldera Medical Inc.
Desara mesh sling, model cal-dsol
Gastroenterology/Urology
03/13/2013

PSS

Terminated

PS130026

Caldera Medical Inc.
Desara mesh
Gastroenterology/Urology
03/13/2013

PSS

Terminated

PS130027

Caldera Medical Inc.
Desara mesh
Gastroenterology/Urology
03/13/2013

PSS

Terminated

PS060003

Cardica, Inc.
C-port distal anastomosis system
General & Plastic Surgery
06/14/2006

Graft Patency and Technical Failure

Completed

PS100009

CareFusion
Maxplus tru-swab positive displacement connector
General Hospital
07/21/2010

BSI rate

Completed

PS100010

CareFusion
Maxplus tru-swab positive displacement connector
General Hospital
07/21/2010

BSI rate

Completed

PS100012

CareFusion
Ivac needle free administration sets
General Hospital
07/21/2010

BSI rate

Other

PS100013

CareFusion
Smartsite needle free valve administration sets
General Hospital
07/21/2010

BSI rate

Other

PS120035

Coloplast Corp
Exair anterior and posterior prolapse repair systems
Obstetrics/Gynecology
01/03/2012

POP AE and Effectiveness rates, registry

Other

PS120036

Coloplast Corp
Exair anterior and posterior prolapse repair systems
Obstetrics/Gynecology
01/03/2012

POP AE and Effectiveness rates, registry

Consolidated

PS120037

Coloplast Corp
Mentor novasilk mesh
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

PS120038

Coloplast Corp
Restorelle polypropylene mesh; Restorelle polypropylene mesh
General & Plastic Surgery
01/03/2012

AE and effectiveness rates

Other

Restorelle P, EZA, EZP, and L models

Other

PS120055

Coloplast Corp
Minimesh polypropylene mesh
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

Restorelle P, EZA and L model

Other

PS120056

Coloplast Corp
Minimesh polypropylene mesh
Obstetrics/Gynecology
01/03/2012

AE and effectiveness rates

Other

Restorelle P, EZA and L models

Other

PS120096

Coloplast Corp
Gyne ideas minitape rp device
Gastroenterology/Urology
01/03/2012

AE and effectiveness rates

Other

PS120097

Coloplast Corp
Minitape urethral sling
Gastroenterology/Urology
01/03/2012

AE and effectiveness rates

Other

PS120098

Coloplast Corp
Minitape urethral sling
Gastroenterology/Urology
01/03/2012

AE and effectiveness rates

Other

PS130012

Coloplast Corp
Mentor suspend sling
General & Plastic Surgery
03/13/2013

PSS

Other

PS130030

Coloplast Corp
Mentor suspend sling
General & Plastic Surgery
03/13/2013

PSS

Other

PS130039

Coloplast Corp
Altis single incision sling system
Gastroenterology/Urology
03/13/2013

AE and effectiveness rates

Completed

PS120106

Coloplast Corp.
Restorelle polypropylene mesh
General & Plastic Surgery
04/09/2012

POP AE and Effectiveness rates, registry

Completed

Restorelle P, EZA, EZP, and L models

Other

PS120039

Cook Biotech Inc.
Surgisis staple line reinforcement
General & Plastic Surgery
01/03/2012

AE and effectiveness rates

Other

PS120109

Cook Biotech Inc.
Surgisis sling
General & Plastic Surgery
04/09/2012

AE & Effectiveness Rates

Terminated

J-PF-POST, J-SLH, J-PFV, J-PF and J-PF-ANT models

Terminated

PS130040

Cook Biotech Inc.

In [46]:
product_name1 = []
product_price1 = []
product_rating1 = []

url = "https://www.flipkart.com/search?p%5B%5D=facets.brand%255B%255D%3DSamsung&sid=tyy%2F4io&sort=recency_desc&ctx=eyJjYXJkQ29udGV4dCI6eyJhdHRyaWJ1dGVzIjp7InRpdGxlIjp7Im11bHRpVmFsdWVkQXR0cmlidXRlIjp7ImtleSI6InRpdGxlIiwiaW5mZXJlbmNlVHlwZSI6IlRJVExFIiwidmFsdWVzIjpbIkxhdGVzdCBTYW1zdW5nIG1vYmlsZXMgIl0sInZhbHVlVHlwZSI6Ik1VTFRJX1ZBTFVFRCJ9fX19fQ%3D%3D&wid=1.productCard.PMU_V2_1&page=2"

headers = {
        "User-Agent": "Mozilla/5.0",
        "Accept": "application/json",
    }
web3 = requests.get(url, headers=headers)
soup = BeautifulSoup(web3.content, "lxml")

box = soup.find("div", class_ = "DOjaWF gdgoEp")

name = box.find_all("div", class_="KzDlHZ")
for n in name:
    product_name1.append(n.text)

price = box.find_all("div", class_="Nx9bqj _4b5DiR")
for n in price:
    product_price1.append(n.text)

rating = box.find_all("div", class_="XQDdHH")
for n in rating:
    product_rating1.append(n.text)

In [47]:
data1 = {"name": product_name1,
        "price": product_price1,
        "rating": product_rating1}
pd.DataFrame(data1)

                                                 name    price rating
0     SAMSUNG galaxy M15 5G (Celestrial Blue, 128 GB)  ₹12,799    4.3
1         SAMSUNG Galaxy F15 5G (Jazzy Green, 128 GB)  ₹12,499    4.1
2      SAMSUNG Galaxy M35 5G (Moonlight Blue, 128 GB)  ₹14,952    4.4
3        SAMSUNG Galaxy F55 5G (Raisin Black, 256 GB)  ₹26,999      4
4         SAMSUNG Galaxy S23 Ultra 5G (Green, 256 GB)  ₹73,480    4.6
5        SAMSUNG Galaxy M14 4G (Sapphire Blue, 64 GB)  ₹13,999    4.1
6   SAMSUNG M15 Prime Edition (Celestial Blue, 128...  ₹12,684    4.4
7          SAMSUNG Galaxy M14 5G (Berry Blue, 128 GB)  ₹12,999    4.2
8                  SAMSUNG Galaxy A05 (Silver, 64 GB)   ₹7,899    4.4
9       SAMSUNG Galaxy M35 5G (DayBreak Blue, 128 GB)  ₹17,195    4.3
10               SAMSUNG Galaxy A16 5G (Gold, 128 GB)  ₹16,499    4.1
11         SAMSUNG Galaxy M15 5G (Blue Topaz, 128 GB)  ₹12,682    4.3
12      SAMSUNG Galaxy A35 5G (Awesome Lilac, 128 GB)  ₹23,982    4.3
13         SAMSUNG Galaxy A16 5G (Blue Black, 128 GB)  ₹16,089    4.2
14        SAMSUNG Galaxy A16 5G (Light Green, 256 GB)  ₹20,999    4.2
15        SAMSUNG Galaxy S24 FE 5G (Graphite, 256 GB)  ₹50,999    4.5
16       SAMSUNG Galaxy A55 5G (Awesome Navy, 256 GB)  ₹36,999    4.4
17         SAMSUNG Galaxy M15 5G (Stone Grey, 128 GB)  ₹13,398    4.3
18     SAMSUNG Galaxy S24+ 5G (Cobalt Violet, 256 GB)  ₹59,999    4.5
19  SAMSUNG Galaxy S23 Ultra 5G (Phantom Black, 25...  ₹73,743    4.6
20      SAMSUNG Galaxy A35 5G (Awesome Lilac, 128 GB)  ₹25,999    4.3
21           SAMSUNG Galaxy A14 5G (Dark Red, 128 GB)  ₹11,499    4.2
22       SAMSUNG Galaxy F55 5G (Raisin Black, 256 GB)  ₹23,999    3.9
23     SAMSUNG M15 Prime Edition (Blue Topaz, 128 GB)  ₹12,669    4.4

In [44]:

product_name = []
product_price = []
product_rating = []

for i in range(1,10):

    url = "https://www.flipkart.com/search?p%5B%5D=facets.brand%255B%255D%3DSamsung&sid=tyy%2F4io&sort=recency_desc&ctx=eyJjYXJkQ29udGV4dCI6eyJhdHRyaWJ1dGVzIjp7InRpdGxlIjp7Im11bHRpVmFsdWVkQXR0cmlidXRlIjp7ImtleSI6InRpdGxlIiwiaW5mZXJlbmNlVHlwZSI6IlRJVExFIiwidmFsdWVzIjpbIkxhdGVzdCBTYW1zdW5nIG1vYmlsZXMgIl0sInZhbHVlVHlwZSI6Ik1VTFRJX1ZBTFVFRCJ9fX19fQ%3D%3D&wid=1.productCard.PMU_V2_1&page="+str(i)

    headers = {
            "User-Agent": "Mozilla/5.0",
            "Accept": "application/json",
        }

    web3 = requests.get(url, headers=headers)
    soup = BeautifulSoup(web3.content, "lxml")

    box = soup.find("div", class_ = "DOjaWF gdgoEp")
    name = box.find_all("div", class_="KzDlHZ")
    for n in name:
        product_name.append(n.text)
    
    price = box.find_all("div", class_="Nx9bqj _4b5DiR")
    for n in price:
        product_price.append(n.text)

    rating = box.find_all("div", class_="XQDdHH")
    for n in rating:
        product_rating.append(n.text)

print(len(product_name))
print(len(product_price))   
print(len(product_rating))

216
216
213

In [45]:
data = {"name": product_name,
        "price": product_price}
pd.DataFrame(data)

                                                  name    price
0            SAMSUNG Galaxy F05 (Twilight Blue, 64 GB)   ₹6,299
1                   SAMSUNG Galaxy A05 (Black, 128 GB)  ₹12,499
2             SAMSUNG Galaxy A05 (Light Green, 128 GB)   ₹8,071
3                  SAMSUNG Galaxy A05 (Silver, 128 GB)   ₹8,113
4                     SAMSUNG A05 (Light Green, 64 GB)   ₹7,660
..                                                 ...      ...
211     SAMSUNG Galaxy F34 5G (Electric Black, 128 GB)  ₹21,999
212       SAMSUNG Galaxy F34 5G (Mystic Green, 128 GB)  ₹19,999
213       SAMSUNG Galaxy F34 5G (Mystic Green, 128 GB)  ₹21,999
214  SAMSUNG Galaxy M34 5G without charger (Midnigh...  ₹14,999
215             SAMSUNG Galaxy Z Flip5 (Cream, 512 GB)  ₹74,999

[216 rows x 2 columns]